version: '3.1'
services:
  flask_microblog:
    image: flask_microblog:1.0
    hostname: flask_microblog
    container_name: flask_microblog
#    command: flask run
    ports:
      - 5000:5000
    environment:
      FLASK_APP: microblog.py

